### ISSUE TITLE
cloudflare.SetRecords: confusing behavior regarding record ID

### ISSUE THREAD

**Issue by stapelberg** [libdns/cloudflare#1]
Currently, the record’s ID must be empty for it to be updated:
https://github.com/libdns/cloudflare/blob/16482ae4e8069b30e6ecef0b4b1fd69c28bd73a2/provider.go#L134-L158

This seems like the opposite of what one would want in that scenario: when passing in an ID, I would expect the record referenced by that ID to be updated.

Can you clarify if this is a logic bug, or intentional?

**Comment by stapelberg** [comment]
The way we’re using this package can be seen in https://github.com/rtr7/router7/commit/ead58ad72cf69d222b8cbe7a18008843aa8673c6

Let us know if you need more details. Thanks!

**Comment by mholt** [comment]
Hm, yeah, in the case of a missing ID, we should probably just look it up and fill it in. Then the rest of the function should simply call updateRecord. I'd be happy to accept a PR to fix it!

**Comment by stapelberg** [comment]
Thanks for the details. I sent https://github.com/libdns/cloudflare/pull/2 to fix this.
