### ISSUE TITLE
Using wrong zone name for sub sub domain

### ISSUE THREAD

**Issue by TheRedScreen64** [libdns/cloudflare#11]
I'm having problems trying to get a wildcard cert for a sub sub domain e.g. *.sub.domain.com.
This is the error i get: 
`[*.sub.domain.com] solving challenges: presenting for challenge: adding temporary record for zone \"sub.domain.com.\": expected 1 zone, got 0 for sub.domain.com.`
I think the problem is that my zone is called domain.com but it tries to find sub.domain.com which doesnt exist.
Maybe I'm wrong but if not, could you please add an option for setting a custom zone that will be used?

PS: I'm using the caddy cloudflare plugin: https://github.com/caddy-dns/cloudflare but from what I can tell from reading their code this is a problem with this lib.

**Comment by mholt** [comment]
What is the domain? I'll do some digging.

**Comment by TheRedScreen64** [comment]
It's trs-cloud.net and i try to get a wildcard cert for *.local.trs-cloud.net

**Comment by TheRedScreen64** [comment]
This is my caddyfile if it helps:
```Caddyfile
*.local.trs-cloud.net {
	tls {
		dns cloudflare {env.DNS_PROVIDER_TOKEN}
	}
}
```

**Comment by TheRedScreen64** [comment]
Are there any updates on this?

**Comment by TheRedScreen64** [comment]
Actually, it seems like the issue resolved itself, although i didn't change the configuration. I can't tell why it didn't work before but I'm glad it does now. Weird that i got this error a week ago but not anymore. I'm gonna close this issue then.

**Comment by TheRedScreen64** [comment]
I've found the reason!
It seems to be caused by my DNS configuration. When I set 1.1.1.1 as the primary and 8.8.8.8 as the secondary DNS using Docker (I run Caddy and therefore this library using Docker), the issue disappeared.
I hope this helps someone with the same problem.

**Comment by pikeas** [comment]
Just bit by this as well! Using Caddy + Cloudflare plugin to answer challenges for an internal subdomain, recently turned up a new service and it was unable to complete the challenge.

When adding `service.internal.example.com`, the plugin errors because the CF API `zones` endpoint does not return `internal.example.com` as a distinct zone (unless configured separately, only possible for enterprise plans).

Changing the Caddy container's upstream DNS to `1.1.1.1` fixed this, though I'm not sure why that should be needed.

**Comment by mholt** [comment]
Caddy has to look up the zone (SOA) records, so if your DNS configuration is off, it will mess up the lookups. Setting a DNS resolver like a public one such as 1.1.1.1 is the normal behavior and will generally fix those issues.

**Comment by pikeas** [comment]
The config **did** use public DNS. To clarify, using non-Cloudflare DNS (eg, 8.8.8.8) failed, the only way I could get it to work was by overriding the default cluster-level DNS upstream for Caddy only, to use Cloudflare's 1.1.1.1.
