### ISSUE TITLE
Message:Invalid request headers 

### ISSUE THREAD

**Issue by jradxl** [libdns/cloudflare#12]
I don't know what is wrong, please can you advise

Keys, Domains edited for privacy/

All Zone, Api Key set with:
Zone, Zone, READ
Zone, DNS, EDIT

Jul 11 12:46:20 u2010a-15 caddy[35154]: {"level":"error","ts":1720698380.737351,"logger":"tls.obtain","msg":"will retry","error":"[abc.rdu.XXXconsulting.uk] Obtain: [abc.rdu.XXXconsulting.uk] solving challenges: presenting for challenge: adding temporary record for zone \"XXXXconsulting.uk.\": got error status: HTTP 400: [{Code:6003 Message:Invalid request headers ErrorChain:[{Code:6111 Message:Invalid format for Authorization header}]}] (order=https://acme-v02.api.letsencrypt.org/acme/order/1828340627/286314110787) (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":2.122602944,"max_duration":2592000}

```
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
     -H "Authorization: Bearer CHANGEDRBesdbmGzESlJ_PPl5IVEX4gI9L9bi" \
     -H "Content-Type:application/json"

{"result":{"id":"CHANGEDe7d53b8849006387614d103","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}

```

```(cloudflare) {
    tls {
      dns cloudflare {"CHANGEDRBesdbmGzESlJ_PPl5IVEX4gI9L9bi"}
    }
}
```
`xcaddy build v2.8.4 --with github.com/caddy-dns/dynu@master --with github.com/caddy-dns/ovh --with github.com/caddy-dns/cloudflare`

```
$ ./caddy build-info | grep dns
dep	github.com/caddy-dns/cloudflare	v0.0.0-20240703190432-89f16b99c18e	h1:POEJXMmSOMJP/73oM/riQTDMg0yjQYlA7nVjyt1+5p8=
dep	github.com/caddy-dns/dynu	v0.1.1	h1:V4z6oQ/Y2hOISNc42IdFV+OANRLKpC5gF3H7mO9cu4k=
dep	github.com/caddy-dns/ovh	v0.0.2	h1:8EQaUw0wWlFnQVigBKTL+o5fCkHqPBh69WCu9peqvIg=
dep	github.com/libdns/cloudflare	v0.1.2-0.20240604123710-0549667a10ab	h1:tX5H3Liz1eTJBbQK2/zs3tmWf79jCKplqQ38AIi/qW4=
dep	github.com/libdns/dynu	v0.1.1	h1:/+1xQpIXDyJu4HAlwjcgYxOgnWt2qKd96hFzXymliVc=
dep	github.com/libdns/libdns	v0.2.2	h1:O6ws7bAfRPaBsgAYt8MDe2HcNBGC29hkZ9MX2eUSX3s=
dep	github.com/libdns/ovh	v0.0.2	h1:9ZBoPi9/BHweKMY609CdvmLVxy3v8WStJJcf+VG5lNI=
dep	github.com/miekg/dns	v1.1.59	h1:C9EXc/UToRwKLhK5wKU/I4QVsBUc8kE6MkHBkeypWZs=

```

**Comment by mholt** [comment]
Did you mean to paste in the `{"` and `"}` too? Just use your key without those.

**Comment by mholt** [comment]
It usually means your credentials are wrong (wrong API key). Duplicate of #6 and #9.
