### ISSUE TITLE
Invalid Request Headers

### ISSUE THREAD

**Issue by goJesscho** [libdns/cloudflare#6]
Does anyone know if this package has fallen out of date with cloudflare, trying to run with the recommended (scoped, Zone:Read, DNS:Edit) I get the following error:

```unable to get TLS for "mx.catcher.mx.ax": mx.catcher.mx.ax: obtaining certificate: [mx.catcher.mx.ax] Obtain: [mx.catcher.mx.ax] solving challenges: presenting for challenge: adding temporary record for zone mx.ax.: got error status: HTTP 400: [{Code:6003 Message:Invalid request headers}] (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/x/x) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)```

**Comment by mholt** [comment]
That's usually the error response when your credentials are missing or malformed or something.
